# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import carritos_pb2 as carritos__pb2
import productos_pb2 as productos__pb2


class CarritosStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearCarrito = channel.unary_unary(
                '/Carritos/CrearCarrito',
                request_serializer=carritos__pb2.Carrito.SerializeToString,
                response_deserializer=carritos__pb2.IdCarrito.FromString,
                )
        self.AgregarItemsCarrito = channel.stream_unary(
                '/Carritos/AgregarItemsCarrito',
                request_serializer=carritos__pb2.Producto_Carrito.SerializeToString,
                response_deserializer=carritos__pb2.ResponseCarrito.FromString,
                )
        self.TraerCarritosByIdUsuario = channel.unary_stream(
                '/Carritos/TraerCarritosByIdUsuario',
                request_serializer=productos__pb2.IdUsuario.SerializeToString,
                response_deserializer=carritos__pb2.Producto_Carrito.FromString,
                )
        self.TraerCarritoById = channel.unary_stream(
                '/Carritos/TraerCarritoById',
                request_serializer=carritos__pb2.IdCarrito.SerializeToString,
                response_deserializer=carritos__pb2.Carrito.FromString,
                )


class CarritosServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CrearCarrito(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgregarItemsCarrito(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TraerCarritosByIdUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TraerCarritoById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarritosServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearCarrito': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearCarrito,
                    request_deserializer=carritos__pb2.Carrito.FromString,
                    response_serializer=carritos__pb2.IdCarrito.SerializeToString,
            ),
            'AgregarItemsCarrito': grpc.stream_unary_rpc_method_handler(
                    servicer.AgregarItemsCarrito,
                    request_deserializer=carritos__pb2.Producto_Carrito.FromString,
                    response_serializer=carritos__pb2.ResponseCarrito.SerializeToString,
            ),
            'TraerCarritosByIdUsuario': grpc.unary_stream_rpc_method_handler(
                    servicer.TraerCarritosByIdUsuario,
                    request_deserializer=productos__pb2.IdUsuario.FromString,
                    response_serializer=carritos__pb2.Producto_Carrito.SerializeToString,
            ),
            'TraerCarritoById': grpc.unary_stream_rpc_method_handler(
                    servicer.TraerCarritoById,
                    request_deserializer=carritos__pb2.IdCarrito.FromString,
                    response_serializer=carritos__pb2.Carrito.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Carritos', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Carritos(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CrearCarrito(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Carritos/CrearCarrito',
            carritos__pb2.Carrito.SerializeToString,
            carritos__pb2.IdCarrito.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AgregarItemsCarrito(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/Carritos/AgregarItemsCarrito',
            carritos__pb2.Producto_Carrito.SerializeToString,
            carritos__pb2.ResponseCarrito.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TraerCarritosByIdUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Carritos/TraerCarritosByIdUsuario',
            productos__pb2.IdUsuario.SerializeToString,
            carritos__pb2.Producto_Carrito.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TraerCarritoById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Carritos/TraerCarritoById',
            carritos__pb2.IdCarrito.SerializeToString,
            carritos__pb2.Carrito.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
