# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: facturas.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='facturas.proto',
  package='facturas',
  syntax='proto3',
  serialized_options=b'\n(io.grpc.springbootkafkaconsumer.facturasB\rfacturasProtoP\001\242\002\003FRP',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x66\x61\x63turas.proto\x12\x08\x66\x61\x63turas\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa9\x01\n\x0bprodFactura\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x02 \x01(\x05\x12\x0e\n\x06precio\x18\x03 \x01(\x02\x12\x18\n\x10nombre_comprador\x18\x04 \x01(\t\x12\x1a\n\x12\x61pellido_comprador\x18\x05 \x01(\t\x12\x17\n\x0fnombre_vendedor\x18\x06 \x01(\t\x12\x19\n\x11\x61pellido_vendedor\x18\x07 \x01(\t\"5\n\ngetFactura\x12\'\n\x08\x61rticulo\x18\x01 \x03(\x0b\x32\x15.facturas.prodFactura\"\x1e\n\tFacturaId\x12\x11\n\tidfactura\x18\x01 \x01(\x05\x32\x45\n\x08\x46\x61\x63turas\x12\x39\n\x0cTraerFactura\x12\x13.facturas.FacturaId\x1a\x14.facturas.getFacturaBA\n(io.grpc.springbootkafkaconsumer.facturasB\rfacturasProtoP\x01\xa2\x02\x03\x46RPb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_PRODFACTURA = _descriptor.Descriptor(
  name='prodFactura',
  full_name='facturas.prodFactura',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nombre', full_name='facturas.prodFactura.nombre', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cantidad', full_name='facturas.prodFactura.cantidad', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='precio', full_name='facturas.prodFactura.precio', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nombre_comprador', full_name='facturas.prodFactura.nombre_comprador', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='apellido_comprador', full_name='facturas.prodFactura.apellido_comprador', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nombre_vendedor', full_name='facturas.prodFactura.nombre_vendedor', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='apellido_vendedor', full_name='facturas.prodFactura.apellido_vendedor', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=231,
)


_GETFACTURA = _descriptor.Descriptor(
  name='getFactura',
  full_name='facturas.getFactura',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='articulo', full_name='facturas.getFactura.articulo', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=286,
)


_FACTURAID = _descriptor.Descriptor(
  name='FacturaId',
  full_name='facturas.FacturaId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idfactura', full_name='facturas.FacturaId.idfactura', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=318,
)

_GETFACTURA.fields_by_name['articulo'].message_type = _PRODFACTURA
DESCRIPTOR.message_types_by_name['prodFactura'] = _PRODFACTURA
DESCRIPTOR.message_types_by_name['getFactura'] = _GETFACTURA
DESCRIPTOR.message_types_by_name['FacturaId'] = _FACTURAID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

prodFactura = _reflection.GeneratedProtocolMessageType('prodFactura', (_message.Message,), {
  'DESCRIPTOR' : _PRODFACTURA,
  '__module__' : 'facturas_pb2'
  # @@protoc_insertion_point(class_scope:facturas.prodFactura)
  })
_sym_db.RegisterMessage(prodFactura)

getFactura = _reflection.GeneratedProtocolMessageType('getFactura', (_message.Message,), {
  'DESCRIPTOR' : _GETFACTURA,
  '__module__' : 'facturas_pb2'
  # @@protoc_insertion_point(class_scope:facturas.getFactura)
  })
_sym_db.RegisterMessage(getFactura)

FacturaId = _reflection.GeneratedProtocolMessageType('FacturaId', (_message.Message,), {
  'DESCRIPTOR' : _FACTURAID,
  '__module__' : 'facturas_pb2'
  # @@protoc_insertion_point(class_scope:facturas.FacturaId)
  })
_sym_db.RegisterMessage(FacturaId)


DESCRIPTOR._options = None

_FACTURAS = _descriptor.ServiceDescriptor(
  name='Facturas',
  full_name='facturas.Facturas',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=320,
  serialized_end=389,
  methods=[
  _descriptor.MethodDescriptor(
    name='TraerFactura',
    full_name='facturas.Facturas.TraerFactura',
    index=0,
    containing_service=None,
    input_type=_FACTURAID,
    output_type=_GETFACTURA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACTURAS)

DESCRIPTOR.services_by_name['Facturas'] = _FACTURAS

# @@protoc_insertion_point(module_scope)
