# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import facturas_pb2 as facturas__pb2
import productos_pb2 as productos__pb2


class FacturasStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearFactura = channel.unary_unary(
                '/Facturas/CrearFactura',
                request_serializer=facturas__pb2.IdProductoCarrito.SerializeToString,
                response_deserializer=facturas__pb2.IdFactura.FromString,
                )
        self.TraerFacturaByIdUsuario = channel.unary_stream(
                '/Facturas/TraerFacturaByIdUsuario',
                request_serializer=productos__pb2.IdUsuario.SerializeToString,
                response_deserializer=facturas__pb2.Factura.FromString,
                )
        self.ImprimirFactura = channel.unary_unary(
                '/Facturas/ImprimirFactura',
                request_serializer=facturas__pb2.IdFactura.SerializeToString,
                response_deserializer=facturas__pb2.ResponseImprimirFactura.FromString,
                )


class FacturasServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CrearFactura(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TraerFacturaByIdUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImprimirFactura(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FacturasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearFactura': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearFactura,
                    request_deserializer=facturas__pb2.IdProductoCarrito.FromString,
                    response_serializer=facturas__pb2.IdFactura.SerializeToString,
            ),
            'TraerFacturaByIdUsuario': grpc.unary_stream_rpc_method_handler(
                    servicer.TraerFacturaByIdUsuario,
                    request_deserializer=productos__pb2.IdUsuario.FromString,
                    response_serializer=facturas__pb2.Factura.SerializeToString,
            ),
            'ImprimirFactura': grpc.unary_unary_rpc_method_handler(
                    servicer.ImprimirFactura,
                    request_deserializer=facturas__pb2.IdFactura.FromString,
                    response_serializer=facturas__pb2.ResponseImprimirFactura.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Facturas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Facturas(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CrearFactura(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Facturas/CrearFactura',
            facturas__pb2.IdProductoCarrito.SerializeToString,
            facturas__pb2.IdFactura.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TraerFacturaByIdUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Facturas/TraerFacturaByIdUsuario',
            productos__pb2.IdUsuario.SerializeToString,
            facturas__pb2.Factura.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ImprimirFactura(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Facturas/ImprimirFactura',
            facturas__pb2.IdFactura.SerializeToString,
            facturas__pb2.ResponseImprimirFactura.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
