# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import facturas_pb2 as facturas__pb2


class FacturasStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TraerFactura = channel.unary_unary(
                '/facturas.Facturas/TraerFactura',
                request_serializer=facturas__pb2.FacturaId.SerializeToString,
                response_deserializer=facturas__pb2.getFactura.FromString,
                )


class FacturasServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TraerFactura(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FacturasServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TraerFactura': grpc.unary_unary_rpc_method_handler(
                    servicer.TraerFactura,
                    request_deserializer=facturas__pb2.FacturaId.FromString,
                    response_serializer=facturas__pb2.getFactura.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'facturas.Facturas', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Facturas(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TraerFactura(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/facturas.Facturas/TraerFactura',
            facturas__pb2.FacturaId.SerializeToString,
            facturas__pb2.getFactura.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
